#!/bin/bash -e

#SBATCH --account       
#SBATCH --job-name      blastx_NCBI_MIBIG
#SBATCH --time          7-00:00:00
#SBATCH --mem           50GB
#SBATCH --cpus-per-task 24
#SBATCH --error         %x_%j.err
#SBATCH --output        %x_%j.out

module purge
module load BLAST/2.13.0-GCC-11.3.0
module load BLASTDB/2024-01

cd [set working directory]

#blastx BGCs against the MIBiG database
blastx -query NRPS_BGC.fa -db MiBiG_DB/MiBiG -outfmt "6 qseqid sseqid evalue pident" -out nrps_MIBiG.csv -num_threads 24 -num_alignments 10
blastx -query PKS_BGC.fa -db MiBiG_DB/MiBiG -outfmt "6 qseqid sseqid evalue pident" -out pks_MIBiG_top10.csv -num_threads 24 -num_alignments 10

#blastx BGCs against the NCBI database
blastx -query NRPS_BGC.fa -db nr -outfmt "6 qseqid sseqid evalue pident" -out nrps_NCBI.csv -num_threads 24 -num_alignments 10
blastx -query PKS_BGC.fa -db nr -outfmt "6 qseqid sseqid evalue pident" -out pks_NCBI.csv -num_threads 24 -num_alignments 10
